runtime: custom
env: flex
service: seatgeek
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
  volumes:
  - name: ramdisk1
    volume_type: tmpfs
    size_gb: 1.5

env_variables:
  GCS_AUTH_FILE: <%= ENV["GCS_AUTH_FILE"] %>
  SEATGEEK_CLIENT_ID: <%= ENV["SEATGEEK_CLIENT_ID"] %>
  SEATGEEK_CLIENT_SECRET: <%= ENV["SEATGEEK_CLIENT_SECRET"] %>
  
handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html
  